--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/r3pt1s/libGame
build-by-default: true
branches:
  - main
projects:
  libGame:
    model: virion
    type: library
    lint:
      phpstan: false
...